import type { DemoRequest } from "./types";

export const MOCK_DEMO_REQUESTS: DemoRequest[] = [
  {
    id: "1",
    agencyName: "Sunrise Tours Pvt. Ltd.",
    agencyType: "Travel Agency",
    website: "https://sunrisetours.com",
    contactName: "Rajesh Kumar",
    contactRole: "Founder & CEO",
    contactEmail: "rajesh@sunrisetours.com",
    contactPhone: "+91-9876543210",
    country: "India",
    city: "Mumbai",
    status: "new",
    assignedTo: "Unassigned",
    date: "10/02/2026",
    requestNotes: "Interested in enterprise plan for our growing agency with 15+ staff members.",
  },
  {
    id: "2",
    agencyName: "Adventure Horizons LLC",
    agencyType: "Tour Operator",
    contactName: "Jennifer Martinez",
    contactRole: "Operations Manager",
    contactEmail: "jennifer@adventurehorizons.com",
    contactPhone: "+1-555-0102",
    country: "United States",
    city: "Denver",
    status: "contacted",
    assignedTo: "Mike Support",
    date: "09/02/2026",
  },
  {
    id: "3",
    agencyName: "Dream Destinations",
    agencyType: "Travel Consultant",
    contactName: "Emma Thompson",
    contactRole: "Owner",
    contactEmail: "emma@dreamdestinations.co.uk",
    contactPhone: "+44-20-1234-5678",
    country: "United Kingdom",
    city: "London",
    status: "scheduled",
    assignedTo: "Sarah Finance",
    date: "08/02/2026",
  },
  {
    id: "4",
    agencyName: "Global Explorers Inc.",
    agencyType: "Corporate Travel",
    contactName: "David Tan",
    contactRole: "Head of Technology",
    contactEmail: "david@globalexplorers.sg",
    contactPhone: "+65-6123-4567",
    country: "Singapore",
    city: "Singapore",
    status: "contacted",
    assignedTo: "Mike Support",
    date: "07/02/2026",
  },
  {
    id: "5",
    agencyName: "Wanderlust Adventures",
    agencyType: "Adventure Tours",
    contactName: "Michael Chen",
    contactRole: "Marketing Director",
    contactEmail: "michael@wanderlustadventures.com.au",
    contactPhone: "+61-2-1234-5678",
    country: "Australia",
    city: "Sydney",
    status: "completed",
    assignedTo: "Sarah Finance",
    date: "05/02/2026",
  },
  {
    id: "6",
    agencyName: "EcoTravel Partners",
    agencyType: "Sustainable Tourism",
    contactName: "Lisa Anderson",
    contactRole: "Executive Director",
    contactEmail: "lisa@ecotravelpartners.org",
    contactPhone: "+1-555-0106",
    country: "Canada",
    city: "Vancouver",
    status: "rejected",
    assignedTo: "Unassigned",
    date: "04/02/2026",
  },
];
