import type { PaymentRow } from "./types";

export const MOCK_PAYMENTS: PaymentRow[] = [
  {
    id: "1",
    invoice: "INV-2026-001",
    userLabel: "User: u1",
    plan: "Premium",
    type: "subscription",
    amount: 19.99,
    method: "Credit Card",
    status: "completed",
    date: "01/02/2026",
  },
  {
    id: "2",
    invoice: "INV-2026-002",
    userLabel: "Agency: ag2",
    plan: "Enterprise",
    type: "subscription",
    amount: 499.0,
    method: "Bank Transfer",
    status: "completed",
    date: "01/02/2026",
  },
  {
    id: "3",
    invoice: "INV-2026-003",
    userLabel: "User: u2",
    plan: "Plus",
    type: "subscription",
    amount: 9.99,
    method: "PayPal",
    status: "completed",
    date: "05/02/2026",
  },
  {
    id: "4",
    invoice: "INV-2026-004",
    userLabel: "Agency: ag1",
    plan: "Pro",
    type: "subscription",
    amount: 249.0,
    method: "Credit Card",
    status: "pending",
    date: "08/02/2026",
  },
  {
    id: "5",
    invoice: "INV-2026-005",
    userLabel: "User: u4",
    plan: "Premium",
    type: "refund",
    amount: 19.99,
    method: "Credit Card",
    status: "refunded",
    date: "07/02/2026",
  },
];
