import type { AppUser } from "./types";

export const MOCK_USERS: AppUser[] = [
  {
    id: "1",
    name: "Sarah Johnson",
    email: "sarah.j@example.com",
    phone: "+1-555-0101",
    subscription: "premium",
    subscriptionExpires: "15/06/2026",
    status: "active",
    totalTrips: 12,
    joined: "15/03/2024",
    linkedAgency: "ag1",
  },
  {
    id: "2",
    name: "Michael Chen",
    email: "michael.c@example.com",
    subscription: "pro",
    status: "active",
    totalTrips: 5,
    joined: "12/04/2024",
  },
  {
    id: "3",
    name: "Emma Wilson",
    email: "emma.w@example.com",
    subscription: "trial",
    status: "active",
    totalTrips: 2,
    joined: "10/05/2024",
  },
  {
    id: "4",
    name: "David Martinez",
    email: "david.m@example.com",
    subscription: "premium",
    subscriptionExpires: "05/06/2026",
    status: "suspended",
    totalTrips: 8,
    joined: "05/06/2024",
  },
  {
    id: "5",
    name: "Lisa Anderson",
    email: "lisa.a@example.com",
    subscription: "pro",
    subscriptionExpires: "20/12/2024",
    status: "active",
    totalTrips: 15,
    joined: "20/12/2024",
  },
];
