// src/components/tables/agencies/mock.ts
import type { Agency } from "./types";

export const MOCK_AGENCIES: Agency[] = [
  {
    id: "1",
    name: "Wanderlust Travel Co.",
    type: "Travel Agency",
    adminName: "Robert Smith",
    email: "contact@wanderlust.com",
    phone: "+1-555-1001",
    registrationNumber: "REG-2024-001",
    verification: "approved",
    subscription: "pro",
    status: "active",
    totalTrips: 342,
    activeTravelers: 156,
    staffCount: 12,
    joined: "15/01/2024",
    revenueContribution: 125400,
  },
  {
    id: "2",
    name: "Global Tours & Adventures",
    type: "Tour Operator",
    adminName: "Michael Chen",
    email: "hello@globaltours.com",
    phone: "+1-555-2002",
    registrationNumber: "REG-2024-018",
    verification: "approved",
    subscription: "enterprise",
    status: "active",
    totalTrips: 587,
    activeTravelers: 289,
    staffCount: 24,
    joined: "10/02/2024",
    revenueContribution: 287600,
  },
  {
    id: "3",
    name: "Adventure Seekers Ltd",
    type: "Adventure Tours",
    adminName: "Emma Wilson",
    email: "team@adventureseekers.com",
    phone: "+1-555-3003",
    registrationNumber: "REG-2024-045",
    verification: "pending",
    subscription: "starter",
    status: "suspended",
    totalTrips: 45,
    activeTravelers: 28,
    staffCount: 6,
    joined: "05/03/2024",
    revenueContribution: 18500,
  },
  {
    id: "4",
    name: "City Break Specialists",
    type: "Travel Agency",
    adminName: "Lisa Anderson",
    email: "support@citybreak.com",
    phone: "+1-555-4004",
    registrationNumber: "REG-2024-071",
    verification: "rejected",
    subscription: "basic",
    status: "blocked",
    totalTrips: 23,
    activeTravelers: 12,
    staffCount: 4,
    joined: "20/04/2024",
    revenueContribution: 8900,
  },
];
